# Generated by Django 5.0.4 on 2024-04-22 18:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='template_es',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='template_fr',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
