# Generated by Django 5.0.4 on 2024-04-22 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_subcategory_template_es_subcategory_template_fr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='template_es',
            new_name='template_kg',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='template_fr',
            new_name='template_ru',
        ),
    ]
