# Generated by Django 5.0.4 on 2024-04-23 09:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_rename_template_es_subcategory_template_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='flight_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^[A-Z]{2,3}\\d{1,4}$', 'Invalid flight number format')]),
        ),
    ]
