# Generated by Django 5.0.4 on 2024-04-23 10:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_subcategory_flight_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='destination',
            field=models.CharField(blank=True, max_length=3, null=True, validators=[django.core.validators.RegexValidator('^[A-Z]{3}$', 'Invalid destination format')]),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='origin',
            field=models.CharField(blank=True, max_length=3, null=True, validators=[django.core.validators.RegexValidator('^[A-Z]{3}$', 'Invalid origin format')]),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='flight_number',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[django.core.validators.RegexValidator('^[A-Z]{2,3}\\d{1,4}$', 'Invalid flight number format')]),
        ),
    ]
