# Generated by Django 5.0.4 on 2024-05-10 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_subcategory_predefined_audio_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='predefined_audio_files',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
